# Generated by Django 3.0.3 on 2020-04-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaildiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=320, unique=True, verbose_name='Email address'),
        ),
    ]
