# Generated by Django 3.0.3 on 2020-04-15 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emaildiary', '0002_auto_20200407_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_remind',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_remind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_remind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='yearly_remind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='yearly_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
