# Generated by Django 3.0.3 on 2020-05-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaildiary', '0003_auto_20200415_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='release_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
